services:
  db:
    env_file:
      - .env
    image: postgres:13.16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_network

  frontend:
    env_file:
      - .env
    build: ./frontend
    volumes:
      - ./frontend:/home/app
      - frontend_node_modules:/home/app/node_modules
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
#    ports:
#      - 3000:3000
#      - 5173:5173

    depends_on:
      - backend
    networks:
      - main_network
    tmpfs:
      - /tmp


  backend:
    env_file:
      - .env
    build: ./backend
    restart: always
    volumes:
      - ./backend:/home/app/
    depends_on:
      - db
    networks:
      - main_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - main_network

volumes:
  postgres_data:
  frontend_node_modules:

networks:
  main_network: