# Generated by Django 5.1.5 on 2025-05-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voshod', '0001_initial'),
    ]

    operations = [
    ]
